
#'bundle exec jekyll serve'
# accessed via {{ site.title }}, {{ site.email }}
# jekyll server --watch --beurl ""


title: My awesome Data Science blog
email: marcelo.cipher@gmail.com.com
description: > # this means to ignore newlines until "baseurl:"
  My Awesome Data Science blog.
baseurl: "/data-science" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marcelo_cipher
github_username: marcelo-cipher 

# Build settings
markdown: kramdown
#theme: minima
#gems:
#  - jekyll-feed
exclude:
  - README.md
#  - Gemfile
#  - Gemfile.lock
